http:
  routers:
    myweb:
      service: my-web
      rule: "Host(`myweb.oom.home`)"
    hello:
      service: hello
      rule: "Host(`myweb.oom.home`) && PathPrefix(`/api/hello`)"
  services:
    myweb:
      loadBalancer:  
        servers:
        - url: 'http://192.168.2.45:9080'
    hello:
      loadBalancer:  
        servers:
        - url: 'http://192.168.41.250:4000'
