

@host = http://localhost:3000
@token = token_from_login
###### Unauthenticated  ######

### Login
POST {{host}}/api/me/login HTTP/1.1
content-type: application/json

{
    "username": "oom",
    "password": "oom"
}

###### Authenticated User ######

### List User
GET {{host}}/api/users HTTP/1.1

### decode token, logined
GET {{host}}/api/me/decode-token HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### get My profile
GET {{host}}/api/me HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Get User profile
GET {{host}}/api/users/oom HTTP/1.1
Authorization: Bearer {{token}}

### Get User list
GET {{host}}/api/users HTTP/1.1
Authorization: Bearer {{token}}

###### Admin role ######

### Create user, admin
POST {{host}}/api/users HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "username": "oom5",
    "password": "oom5",
    "email":"oom5@xxx.com",
    "role":["user"]
}
### Update user, admin
PUT {{host}}/api/users/oom HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "email":"oomxxx@yyy.com"
}
### Delete user
DELETE {{host}}/api/users/oom1 HTTP/1.1
Authorization: Bearer {{token}}

