
GET http://localhost:3000/api/users HTTP/1.1

###
GET http://localhost:3000/api/users/info/oom HTTP/1.1
###
POST http://localhost:3000/api/users HTTP/1.1
content-type: application/json

{
    "username": "oom",
    "password": "oomja",
    "email":"oom@xxx.com"
}
###

PUT http://localhost:3000/api/users/update/oom HTTP/1.1
content-type: application/json

{
    "email":"oom@xxx.com"
}
###
DELETE http://localhost:3000/api/users/delete/oom HTTP/1.1
###
POST http://localhost:3000/api/users/login HTTP/1.1
content-type: application/json

{
    "username": "oom",
    "password": "oomja"
}
###
GET http://localhost:3000/api/users/hello HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9vbSIsImVtYWlsIjoib29tQHh4eC5jb20iLCJyb2xlIjpbXSwiaWF0IjoxNzI5MTkyOTYyLCJleHAiOjE3MjkxOTQ3NjJ9.jJWVDXypGr_pamEaPwZ405uE7iBXL0LE2CBAa4-BoNoeBAG_1ai6btH3XHR33S7L2C-csAs3OlNGWklneYaGOlKBtYV-VINi63fTDVjf9xe3aTIPcLWMqn97qCC0VXTX11i3AkAvcI2-ffkisK3WXkYWeNntxdgbFIDe37QBulYvlDAPYSJf3jYZ9xsltJ1WQJ2INLrLzJoNVDxu3NbHFTEARiDt9vkpPc_J2bkCAkc5vRq03frMNfSKSuMO-Gn8uso6ZvXTxXliD0BLwL68Q2CetJHaxB3x_hn9tBdv7oPBavGCOsQajhC6T2oXwgDi0I1vs-DvqV1cXgGj1KgoHkLobpQl3LZiwCJI3nPDM1J5jRfwZnGQ60SAvHzJ2MdP7C6xsrzt3QqV7I1cV1sskL-X85NR2ERgapB0RAKnU85R9tnKZS61d-I7L2qvMQSBVWjMaqvz-4c63XQuqa3SDgLbvqqRhZa_Z8mJRwuTQRIwcX8Liml7Cb3Sn6YKFivwxqxSrN47vEtCZLR7nAKRFLgx7WYehRBOg5rGmJRxJMvHaf695zIWdqgZYneCSYZ5WhfZDiaC0T9UueVCxeWBVJ2S8UEupZMA7MrXumjMMF1I5kk9HBLIworB36KgJkBymYkrVzJVcFKS4FnUde5uu95CvLeigJUpzGWf3DFSffc
###
GET http://localhost:3000/api/users/decode-token HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9vbSIsImVtYWlsIjoib29tQHh4eC5jb20iLCJyb2xlIjpbXSwiaWF0IjoxNzI5MTk0ODA4LCJleHAiOjE3MjkxOTY2MDh9.HIlFwVu-5vjy__dG1f0_kNl38ysU-qLAOwACHwLL3RPbU_vmycSEW241eSwdzEHlvwMOLwRTXYRFEaSHgL9XOMEba2YzaA8ED0J_qbNp8_60j1sZ96s3JuzRvFuXuq2Oz-urnjlTQMb8XaSKsXCAV4WLtXbynuzEsAIG73fsqLWeakGz_P_6npeeVHjOfKdpbNEQjSbcd8I1JcZac6kj_6tbR9tx7ErGrTr6W2kfeeGlZB1fAM0kznBPMqCbr3gj-u1ttKwGtpUS4KuUEccIGYhA1TVz-C4qCH3WCsWbj5BWwtWDUXZt1VY5lCzL59tx88HDKDm3d0E31JqWV_NM9D0o61QNucIowpEdYMlVIDzUdS8IHNb2soyiqH-2GtTxIpRdoJ-IzObtz514u8xsC0sJ6Ha4Pn5u-f059bXbbEa5MGgieK0j_mc9XWykjxiUUqzaG89uS-HP0QKOKmM6yXAtoLKhsfWwdmWZ0JG5yG85wcBn_y4mYWJczLz3y7x2hEosfHqiFP7PkBkEuRfghvlbR9bCWF8BTpNQDqlw-x2_uhE8MFwIsW8WVWEHj3GSd7viQKB5rvItIwc_DgDTEH-02M2zcoLMWEFtgGcTRcxKGczs3UOsWIBvOvubtXdGcyWbBjDXERuDZMenl2EZS9AN1UfDB8xtu79UlYXxcT0
###
