# Install Rest client extension for Visual Studio code before use
@host = http://localhost:4000

########## basic
GET {{host}}/api/myapi

########## fruit
###
GET {{host}}/api/fruits
Accept: application/json
###
GET {{host}}/api/fruits/1
Accept: application/json
###
PATCH {{host}}/api/fruits/1
content-type: application/json

{
  "color": "blue"
}
###
POST {{host}}/api/fruits
content-type: application/json

{
  "name": "Coconut",
  "color": "green"
}

###
DELETE {{host}}/api/fruits/2
content-type: application/json

########## TSOA
### no validate
GET {{host}}/hello/My-Controller
Accept: application/json
###
POST {{host}}/hello
content-type: application/json
Accept: application/json

{"msg":"How are you?"}
###
PATCH {{host}}/hello
content-type: application/json
Accept: application/json

{"msg":"Who are you?"}
###
DELETE {{host}}/hello?id=123
content-type: application/json
Accept: application/json

### with Zod validate
GET {{host}}/helloZod/oom
Accept: application/json
###
POST {{host}}/helloZod
content-type: application/json
Accept: application/json

{"id":0,"msg":"xx"}
