services:    
  sso:
    user: 1000:1000
    image: quay.io/keycloak/keycloak:25.0.0
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./keycloak_data:/opt/keycloak/data
    command:
      - start-dev
      # - --features=token-exchange,organization
      # - --hostname-url=http://192.168.2.101:3022
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - TZ=Asia/Bangkok
    ports:
      - "3022:8080"