version: '3.8'

services:
  dev:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        GIT_USERNAME: ${GIT_USERNAME}
        GIT_EMAIL: ${GIT_EMAIL}
    container_name: sample-dev-container
    volumes:
      - ..:/workspace:cached
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
    # Keep the container alive and give it an init (PID 1 signal handling)
    command: /bin/sh -lc "trap 'exit 0' TERM; while sleep 3600; do :; done"
    tty: true
    init: true
    # If you use ADB over Wi-Fi, usually no port is needed, but if connecting to host device:
    # network_mode: host  # On macOS, useful not in compose but with separate builder