networks:
  dev:
    external: true
services:
  demo:
    image: docker.frappet.com/training/oom_express:0.0.1
    ports:
        - 4001:80
    networks:
      - dev
    labels:
      - traefik.enable=true
      - traefik.http.routers.dev-docker.rule=Host(`app.local`) && (Path(`/api/fruits`)) 