networks:
  proxy:
    external: true
services:
  fe:
    image: docker.frappet.com/training/fe:latest
    ports:
    - "3001:80"
    environment:
      - TZ=Asia/Bangkok
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.fe.rule=Host(`fe.oom.home`)"
    # networks:
    #  - traefik
